### ISSUE TITLE
Dagger 2 injection of DataSource need to be revised.

### ISSUE THREAD

**Issue by genaforvena** [genaforvena/StreetArtView#1]
I have some concerns injecting Realm as singleton for the whole application. Realm instance need to be closed after it is no longer needed. Maybe if we continue using Realm as singleton no issue will be observed but still.

**Comment by genaforvena** [comment]
There are some issues on that observed.
Our Realm object is created in the thread that we do not control. Once it is created it is not recreated after that. So if we'll try to insert something from background thread in this injected datasource - we'll get  `java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.`

Example of this issue:

```
02-16 13:21:07.008 7559-7867/org.imozerov.streetartview E/AndroidRuntime: FATAL EXCEPTION: IntentService[FetchService]
                                                                          Process: org.imozerov.streetartview, PID: 7559
                                                                          java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
                                                                              at io.realm.BaseRealm.checkIfValid(BaseRealm.java:349)
                                                                              at io.realm.BaseRealm.beginTransaction(BaseRealm.java:280)
                                                                              at io.realm.Realm.beginTransaction(Realm.java:108)
                                                                              at org.imozerov.streetartview.storage.DataSourceKt.batchInsertOrUpdate(DataSource.kt:86)
                                                                              at org.imozerov.streetartview.storage.DataSource.insert(DataSource.kt:28)
                                                                              at org.imozerov.streetartview.network.FetchService.handleStartFetchAction(FetchService.kt:43)
                                                                              at org.imozerov.streetartview.network.FetchService.onHandleIntent(FetchService.kt:29)
                                                                              at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:146)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by genaforvena** [comment]
#85 is a related issue.
